#! /bin/bash

docker run -d --name homeassistant --privileged \
--restart=unless-stopped \
-e TZ=America/Los_Angeles \
-v /home/jmfife/projects/homeassistant-jmfife/config:/config \
-v /run/dbus:/run/dbus:ro \
--network=host ghcr.io/home-assistant/home-assistant:stable
